name: Build and Test .NET App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest  # Run on Linux

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET with caching
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        cache: true
        cache-dependency-path: '**/packages.lock.json'  # Ensure NuGet cache works

    - name: Restore dependencies
      run: dotnet restore --use-lock-file

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-restore --verbosity normal
